### ISSUE TITLE
"Add additional method metadata" breaks compatibility with veewee/xml <3.0.0

### ISSUE THREAD

**Issue by lstrojny** [php-soap/wsdl-reader#30]
### Bug Report

Current version broken with veewee/xml <3.0.0
 

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

#### Summary

https://github.com/php-soap/wsdl-reader/commit/172ca5bdad9c686005506e30e1bb95baa7da3780 introduces `Soap\WsdlReader\Parser\Definitions\TargetNamespaceParser` which uses `VeeWee\Xml\Dom\Document::locateDocumentElement` which is only available in `veewee/xml` >=3.0.0.
Still, composer.json states compatibility with `veewee/xml` `^2.6 || ^3.0`

#### Current behaviour

```
Fatal error: Uncaught Error: Call to undefined method VeeWee\Xml\Dom\Document::locateDocumentElement() in /src/vendor/php-soap/wsdl-reader/src/Parser/Definitions/TargetNamespaceParser.php:13
```

#### How to reproduce

1. Install php-soap/wsdl-reader with --prefer-lowest
2. Run code generation
3. Boom

#### Expected behaviour

Either properly support < 3.0.0 or change version requirements

**Comment by lstrojny** [comment]
Could be helpful to introduce a build matrix option with `--prefer-lowest` in https://github.com/php-soap/wsdl-reader/blob/main/.github/workflows/tests.yaml

**Comment by veewee** [comment]
Oh snap .. :)
Thanks for reporting. I don't see a reason not to just bump to v3 here.

Do you mind sending a PR?

**Comment by lstrojny** [comment]
Done. @veewee can you approve the workflow in #31 so the matrix can run?
